name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.2.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.2.3
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^4.1.0
  collection: ^1.15.0
  intl: ^0.17.0
  # TODO: this is bad!
  flutter_sheet_localization:
    git:
      url: https://github.com/spirifoxy/flutter_sheet_localization.git
      path: flutter_sheet_localization
  localization_builder:
    git:
      url: https://github.com/spirifoxy/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.0.2

#dependency_overrides:
#  flutter_sheet_localization:
#    path: ../flutter_sheet_localization
